# This is a basic workflow to help you get started with Actions

name: CI test

env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-scan:
    # The type of runner that the job will run on
    name: Build and scan image
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build the image
        run: docker build -t ubuntu-latest .

      - name: Prisma Cloud image scan
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1.6.4
        with:
          pcc_console_url: https://asia-southeast1.cloud.twistlock.com/aws-singapore-961144797
          pcc_user: joyzy0113@gmail.com
          pcc_pass: Achieve1993122.
          image_name: ubuntu-latest
